### ISSUE TITLE
TopMG. Parallel performance

### ISSUE THREAD

**Issue by liv-acollins** [toppic-suite/toppic-suite#8]
Hi developers,

We are currently running topmg to process a few scans (2-5?) however, we are searching Phospho data. We have set the thread count to 40 but only seeing 1 thread being used. Currently the process has been running for 20 hours.

Command:
`topmg -i TopPTMs.txt **-u 40** -s 2 -G 8 -g -x database.fasta spectra.msalign`

Log:
```
TopMG 1.6.1
********************** Parameters ***********************
Protein database file:                          database.fasta
Spectrum file:                                  spectra.msalign
Fragmentation method:                           FILE
Search type:                                    TARGET
Fixed modifications:                            None
Use TopFD feature file:                         False
Error tolerance for matching masses:            10 ppm
Error tolerance for identifying PrSM clusters:  1.2 Da
Spectrum-level cutoff type:                     EVALUE
Spectrum-level cutoff value:                    0.01
Proteoform-level cutoff type:                   EVALUE
Proteoform-level cutoff value:                  0.01
Allowed N-terminal forms:                       NONE,NME,NME_ACETYLATION,M_ACETYLATION
Maximum mass shift of modifications:            500 Da
**Thread number:                                  40**
Modification file name:                         TopPTMs.txt
Gap in proteoform graph:                        40
Maximum number of variable PTMs:                5
Maximum number of variable PTMs in a graph gap: 8
Maximum number of unexpected modifications:     2
Report only proteoforms from whole proteins:    False
Executable file directory:                      /software/toppic/1.6.1/usr/bin
Start time:                                     Thu Feb 16 14:34:49 2023
Version:                                        1.6.1
Variable PTM Begin
Oxidation                                       15.994915
Phospho                                         79.966331
Variable PTM End
********************** Parameters ***********************
ASF-One PTM filtering - started.
```

CPU monitoring:
![image](https://user-images.githubusercontent.com/1191435/219647389-69d355e2-c88c-480b-87c6-07a73c7160cf.png)

The log shows that -u argument is being parsed. However, it seems TopMG is not creating multiple threads and only running single threaded. Is this behaviour expected?

**Comment by toppic-suite** [comment]
Hi, Detritus,

Can you let us know the size of your protein sequence database?

Best,

Xiaowen

From: detritus ***@***.***>
Reply-To: toppic-suite/toppic-suite ***@***.***>
Date: Friday, February 17, 2023 at 5:57 AM
To: toppic-suite/toppic-suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [toppic-suite/toppic-suite] TopMG. Parallel performance (Issue #8)


Hi developers,

We are currently running topmg to process a few scans (2-5?) however, we are searching Phospho data. We have set the thread count to 40 but only seeing 1 thread being used. Currently the process has been running for 20 hours.

Command:
topmg -i TopPTMs.txt -u 40 -s 2 -G 8 -g -x database.fasta spectra.msalign

Log:

TopMG 1.6.1

********************** Parameters ***********************

Protein database file:                          database.fasta

Spectrum file:                                  spectra.msalign

Fragmentation method:                           FILE

Search type:                                    TARGET

Fixed modifications:                            None

Use TopFD feature file:                         False

Error tolerance for matching masses:            10 ppm

Error tolerance for identifying PrSM clusters:  1.2 Da

Spectrum-level cutoff type:                     EVALUE

Spectrum-level cutoff value:                    0.01

Proteoform-level cutoff type:                   EVALUE

Proteoform-level cutoff value:                  0.01

Allowed N-terminal forms:                       NONE,NME,NME_ACETYLATION,M_ACETYLATION

Maximum mass shift of modifications:            500 Da

**Thread number:                                  40**

Modification file name:                         TopPTMs.txt

Gap in proteoform graph:                        40

Maximum number of variable PTMs:                5

Maximum number of variable PTMs in a graph gap: 8

Maximum number of unexpected modifications:     2

Report only proteoforms from whole proteins:    False

Executable file directory:                      /software/toppic/1.6.1/usr/bin

Start time:                                     Thu Feb 16 14:34:49 2023

Version:                                        1.6.1

Variable PTM Begin

Oxidation                                       15.994915

Phospho                                         79.966331

Variable PTM End

********************** Parameters ***********************

ASF-One PTM filtering - started.

CPU monitoring:
[Image removed by sender. image]<https://user-images.githubusercontent.com/1191435/219647389-69d355e2-c88c-480b-87c6-07a73c7160cf.png>

The log shows that -u argument is being parsed. However, it seems TopMG is not creating multiple threads and only running single threaded. Is this behaviour expected?

**Comment by liv-acollins** [comment]
The FASTA file contains only a single protein sequence.

**Comment by liuxiaowen** [comment]
There is a bug in the code. We will fix it and keep you updated.

**Comment by liv-acollins** [comment]
Fantastic, happy to test once you have a fix. :)

**Comment by liv-acollins** [comment]
Hi @liuxiaowen,

Do you have any estimate of when the fix might be available?

**Comment by liuxiaowen** [comment]
I will fix it in about a week. If you would like to use TopMG now, you can download version 1.5.5, which does not have the bug. 

https://www.toppic.org/software/toppic_backup/toppic_1.5/register.html

**Comment by liv-acollins** [comment]
Thanks for the quick update @liuxiaowen. This issue looks like it might also be in 1.5.5 :(

`2838616 ..       20   0  568148  15740  11900 S  **99.7**   0.0   7:01.06 topmg -i TopPTMs.txt -u 40 -s 2 -G 8 -g -x database.fasta spectra.msalign`

![image](https://user-images.githubusercontent.com/1191435/220963141-13d424e8-43f3-40e9-950d-5301bfb66986.png)

Admittedly only running 10 minutes so far, but the database & data is quite small so shouldn't be stuck in IO.
Output:
```
TopMG 1.5.5
********************** Parameters ***********************
Protein database file:                          database.fasta
Spectrum file:                                  spectra.msalign
Fragmentation method:                           FILE
Search type:                                    TARGET
Fixed modifications:                            None
Use TopFD feature file:                         False
Error tolerance for matching masses:            15 ppm
Error tolerance for identifying PrSM clusters:  1.2 Da
Spectrum-level cutoff type:                     EVALUE
Spectrum-level cutoff value:                    0.01
Proteoform-level cutoff type:                   EVALUE
Proteoform-level cutoff value:                  0.01
Allowed N-terminal forms:                       NONE,NME,NME_ACETYLATION,M_ACETYLATION
Maximum mass shift of modifications:            500 Da
Thread number:                                  40
Modification file name:                         TopPTMs.txt
Gap in proteoform graph:                        40
Maximum number of variable PTMs:                5
Maximum number of variable PTMs in a graph gap: 8
Maximum number of unexpected modifications:     2
Report only proteoforms from whole proteins:    False
Executable file directory:                      /software/toppic/1.5.5/usr/bin
Start time:                                     Thu Feb 23 15:56:34 2023
Version:                                        1.5.5
Variable PTM Begin
Oxidation                                       15.994915
Phospho                                         79.966331
Variable PTM End
********************** Parameters ***********************
ASF-One PTM filtering - started.
```

**Comment by liuxiaowen** [comment]
Detritus, 

Thank you for letting us know. We will fix it in about one week. 

Xiaowen

**Comment by liuxiaowen** [comment]
Hi, Detritus, 

We have fixed the issue in version 1.6.2. Please test it. When you test the new version, **please move you sequence and spectrum files to a new folder.** 

Thank you. 

Xiaowen

**Comment by liv-acollins** [comment]
Hi @liuxiaowen,

It looks like this also hasn't fixed the issue. We are still seeing topmg only using 1 core. I'm happy to share the data we are using if you would like to look into this further?

Thanks,
Andrew

**Comment by liv-acollins** [comment]
Hi @liuxiaowen,

Sorry, my mistake. It looks like this is fixed. It looks like we misread this part: **please move you sequence and spectrum files to a new folder** as we accidentally moved the temporary files that topmg produces.

When running this with a clean copy of the database & spectra it works. Topmg now terminates within a couple minutes. I also went back to check 1.6.1 with a clean copy of the data, the issue is still there. So 1.6.2 is definitely a fix for this. :)

**Comment by liv-acollins** [comment]
Also, just to confirm. The issue with the installer is also solved now. Thanks for fixing both of these so quickly.

**Comment by liuxiaowen** [comment]
Detritus, You are welcome.
